//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSide.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ANNOUNCEMENTS
    {
        public int A_ID { get; set; }
        [Required(ErrorMessage = "Lütfen duyuru basligi giriniz.")]
        [StringLength(100, ErrorMessage = "Duyuru basligi uzunlugu maksimum 100 karakter olabilir.")]
        public string A_TITLE { get; set; }
        [Required(ErrorMessage = "Lütfen duyuru icerigi giriniz.")]
        [StringLength(100, ErrorMessage = "Duyuru icerigi uzunlugu maksimum 400 karakter olabilir.")]
        public string A_CONTENT { get; set; }
    }
}
