//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSide.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AREA()
        {
            this.CITY = new HashSet<CITY>();
        }

        [Required(ErrorMessage = "Lütfen bolge adi giriniz.")]
        public int AREA_ID { get; set; }
        [Required(ErrorMessage = "Lütfen bölge adi giriniz.")]
        [StringLength(100, ErrorMessage = "Bolge adi uzunlugu maksimum 100 karakter olabilir.")]
        public string AREA_NAME { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITY> CITY { get; set; }
    }
}
