//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSide.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACILITY_PICTURES
    {
        public int FP_ID { get; set; }
        public int F_ID { get; set; }
        public string FP_PICTURE { get; set; }
    
        public virtual FACILITY FACILITY { get; set; }
    }
}
