//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSide.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVATION()
        {
            this.WAITED_USERS = new HashSet<WAITED_USERS>();
        }
    
        public int RESERVATION_ID { get; set; }
        public int USER_ID { get; set; }
        public int FACILITY_ID { get; set; }
        public System.DateTime DT_BEGIN { get; set; }
        public System.DateTime DT_END { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> COUNT { get; set; }
        public string R_HISTORY { get; set; }
    
        public virtual FACILITY FACILITY { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAITED_USERS> WAITED_USERS { get; set; }
    }
}
