//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSide.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SLIDER
    {
        public int SLIDER_ID { get; set; }
        [Required(ErrorMessage = "Lütfen slider fotografi giriniz.")]
        public string SLIDER_PICTURE { get; set; }
        [Required(ErrorMessage = "Lütfen slider aciklamasi giriniz.")]
        [StringLength(50, ErrorMessage = "Slider aciklamasi uzunlugu maksimum 400 karakter olabilir.")]
        public string SLIDER_DESCRIPTION { get; set; }
    }
}
