//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSide.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsSideEntities : DbContext
    {
        public SportsSideEntities()
            : base("name=SportsSideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREA> AREA { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<DISTRICT> DISTRICT { get; set; }
        public virtual DbSet<FACILITY> FACILITY { get; set; }
        public virtual DbSet<FACILITY_PICTURES> FACILITY_PICTURES { get; set; }
        public virtual DbSet<FACILITY_TYPE> FACILITY_TYPE { get; set; }
        public virtual DbSet<SLIDER> SLIDER { get; set; }
        public virtual DbSet<WAITED_USERS> WAITED_USERS { get; set; }
        public virtual DbSet<ANNOUNCEMENTS> ANNOUNCEMENTS { get; set; }
        public virtual DbSet<RESERVATION> RESERVATION { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<SUBSCRIBER> SUBSCRIBER { get; set; }
    }
}
