//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSide.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.FACILITY = new HashSet<FACILITY>();
            this.RESERVATION = new HashSet<RESERVATION>();
            this.WAITED_USERS = new HashSet<WAITED_USERS>();
            this.WAITED_USERS1 = new HashSet<WAITED_USERS>();
            this.SUBSCRIBER = new HashSet<SUBSCRIBER>();
        }
    
        public int USER_ID { get; set; }
        public int USER_DISTRICT { get; set; }
        public string USER_NAME { get; set; }
        public string USER_SURNAME { get; set; }
        public string USER_MAIL { get; set; }
        public string USER_GSM { get; set; }
        public string USER_TYPE { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_FIRST_NAME { get; set; }
        public Nullable<int> USER_POS { get; set; }
        public Nullable<int> USER_NEG { get; set; }
    
        public virtual DISTRICT DISTRICT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACILITY> FACILITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATION> RESERVATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAITED_USERS> WAITED_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAITED_USERS> WAITED_USERS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBSCRIBER> SUBSCRIBER { get; set; }
    }
}
