//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DISTRICT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISTRICT()
        {
            this.FACILITies = new HashSet<FACILITY>();
            this.USERS = new HashSet<USER>();
        }
        [Required(ErrorMessage = "Lütfen ilçenizi seçiniz.")]
        public int DISTRICT_ID { get; set; }
        [Required(ErrorMessage = "Lütfen sehir seciniz.")]
        public int CITY_ID { get; set; }
        [Required(ErrorMessage = "Lütfen ilce adi giriniz.")]
        [StringLength(100, ErrorMessage = "Ilce adi uzunlugu maksimum 100 karakter olabilir.")]
        public string DISTRICT_NAME { get; set; }
        [Range(1, Int32.MaxValue, ErrorMessage = "Posta kodu minimum 1 olabilir.")]
        public Nullable<int> DISTRICT_ZIP_CODE { get; set; }

        public virtual CITY CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACILITY> FACILITies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
    }
}
