//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FACILITY_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACILITY_TYPE()
        {
            this.FACILITies = new HashSet<FACILITY>();
        }

        public int FT_ID { get; set; }
        [Required(ErrorMessage = "Lütfen tesis turu adi giriniz.")]
        [StringLength(50, ErrorMessage = "Tesis turu uzunlugu maksimum 100 karakter olabilir.")]
        public string FT_NAME { get; set; }
        public string FT_PICTURE { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACILITY> FACILITies { get; set; }
    }
}
