//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.FACILITies = new HashSet<FACILITY>();
            this.RESERVATIONs = new HashSet<RESERVATION>();
            this.WAITED_USERS = new HashSet<WAITED_USERS>();
            this.WAITED_USERS1 = new HashSet<WAITED_USERS>();
            this.SUBSCRIBERs = new HashSet<SUBSCRIBER>();
        }

        public int USER_ID { get; set; }
        [Required(ErrorMessage = "Lütfen ilce seciniz.")]
        public int USER_DISTRICT { get; set; }
        public string USER_NAME { get; set; }
        [Required(ErrorMessage = "Lütfen soyadinizi giriniz.")]
        [StringLength(100, ErrorMessage = "Soyad uzunlugu maksimum 50 karakter olabilir.")]
        public string USER_SURNAME { get; set; }
        [EmailAddress(ErrorMessage = "Gecersiz email adresi")]
        [Required(ErrorMessage = "Lütfen mailinizi giriniz.")]
        [StringLength(100, ErrorMessage = "Mail uzunlugu maksimum 50 karakter olabilir.")]
        public string USER_MAIL { get; set; }
        [Required(ErrorMessage = "Lütfen telefon numaranizi giriniz.")]
        [StringLength(100, ErrorMessage = "Telefon numarasi uzunlugu maksimum 50 karakter olabilir.")]
        [DataType(DataType.PhoneNumber)]
        public string USER_GSM { get; set; }
        public string USER_TYPE { get; set; }
        [Required(ErrorMessage = "Lütfen sifrenizi giriniz.")]
        [StringLength(100, ErrorMessage = "Sifre uzunlugu maksimum 20 karakter olabilir.")]
        public string USER_PASSWORD { get; set; }
        [Required(ErrorMessage = "Lütfen adinizi giriniz.")]
        [StringLength(100, ErrorMessage = "Ad uzunlugu maksimum 50 karakter olabilir.")]
        public string USER_FIRST_NAME { get; set; }
        public Nullable<int> USER_POS { get; set; }
        public Nullable<int> USER_NEG { get; set; }
    
        public virtual DISTRICT DISTRICT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACILITY> FACILITies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATION> RESERVATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAITED_USERS> WAITED_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAITED_USERS> WAITED_USERS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBSCRIBER> SUBSCRIBERs { get; set; }
    }
    public class GoogleGeoCodeResponse
    {

        public string status { get; set; }
        public results[] results { get; set; }

    }

    public class results
    {
        public string formatted_address { get; set; }
        public geometry geometry { get; set; }
        public string[] types { get; set; }
        public address_component[] address_components { get; set; }
    }

    public class geometry
    {
        public string location_type { get; set; }
        public location location { get; set; }
    }

    public class location
    {
        public string lat { get; set; }
        public string lng { get; set; }
    }

    public class address_component
    {
        public string long_name { get; set; }
        public string short_name { get; set; }
        public string[] types { get; set; }
    }
}
